package com.innovation.followers.android.apps.GoldenCook;

import android.app.Activity;
import android.os.Bundle;
import android.widget.TextView;

public class Description extends Activity {
	int Recipe_Names[][] = {{R.string.Catagory1_Recepie1	
			,R.string.Catagory1_Recepie2	
			,R.string.Catagory1_Recepie3	
			,R.string.Catagory1_Recepie4	
			,R.string.Catagory1_Recepie5	
			,R.string.Catagory1_Recepie6	
			,R.string.Catagory1_Recepie7	
			,R.string.Catagory1_Recepie8	
			,R.string.Catagory1_Recepie9	
			,R.string.Catagory1_Recepie10	
			,R.string.Catagory1_Recepie11},{
			R.string.Catagory2_Recepie1
			,R.string.Catagory2_Recepie2
			,R.string.Catagory2_Recepie3
			,R.string.Catagory2_Recepie4
			,R.string.Catagory2_Recepie5
			,R.string.Catagory2_Recepie6
			,R.string.Catagory2_Recepie7
			,R.string.Catagory2_Recepie8
			,R.string.Catagory2_Recepie9
			,R.string.Catagory2_Recepie10
			,R.string.Catagory2_Recepie11
			,R.string.Catagory2_Recepie12
			,R.string.Catagory2_Recepie13
			,R.string.Catagory2_Recepie14
			,R.string.Catagory2_Recepie15
			,R.string.Catagory2_Recepie16
			,R.string.Catagory2_Recepie17
			,R.string.Catagory2_Recepie18
			,R.string.Catagory2_Recepie19
			,R.string.Catagory2_Recepie20
			,R.string.Catagory2_Recepie21
			,R.string.Catagory2_Recepie22
			,R.string.Catagory2_Recepie23
			,R.string.Catagory2_Recepie25
			,R.string.Catagory2_Recepie26
			,R.string.Catagory2_Recepie27
			,R.string.Catagory2_Recepie28
			,R.string.Catagory2_Recepie29
			,R.string.Catagory2_Recepie30
			,R.string.Catagory2_Recepie31
			,R.string.Catagory2_Recepie32
			,R.string.Catagory2_Recepie33
			,R.string.Catagory2_Recepie34
			,R.string.Catagory2_Recepie35
			,R.string.Catagory2_Recepie37
			,R.string.Catagory2_Recepie38
			,R.string.Catagory2_Recepie39
			,R.string.Catagory2_Recepie40
			,R.string.Catagory2_Recepie41
			,R.string.Catagory2_Recepie42
			,R.string.Catagory2_Recepie43
			,R.string.Catagory2_Recepie44
			,R.string.Catagory2_Recepie45
			,R.string.Catagory2_Recepie46
			,R.string.Catagory2_Recepie47
			,R.string.Catagory2_Recepie48
			,R.string.Catagory2_Recepie49
			,R.string.Catagory2_Recepie50
			,R.string.Catagory2_Recepie51},{
			R.string.Catagory3_Recepie1
			,R.string.Catagory3_Recepie2
			,R.string.Catagory3_Recepie3
			,R.string.Catagory3_Recepie4
			,R.string.Catagory3_Recepie5
			,R.string.Catagory3_Recepie6
			,R.string.Catagory3_Recepie7
			,R.string.Catagory3_Recepie8
			,R.string.Catagory3_Recepie9
			,R.string.Catagory3_Recepie10
			,R.string.Catagory3_Recepie11
			,R.string.Catagory3_Recepie12
			,R.string.Catagory3_Recepie13
			,R.string.Catagory3_Recepie14
			,R.string.Catagory3_Recepie15
			,R.string.Catagory3_Recepie16
			,R.string.Catagory3_Recepie17
			,R.string.Catagory3_Recepie18
			,R.string.Catagory3_Recepie19
			,R.string.Catagory3_Recepie20
			,R.string.Catagory3_Recepie21
			,R.string.Catagory3_Recepie22
			,R.string.Catagory3_Recepie23
			,R.string.Catagory3_Recepie24
			,R.string.Catagory3_Recepie25
			,R.string.Catagory3_Recepie26
			,R.string.Catagory3_Recepie27
			,R.string.Catagory3_Recepie28
			,R.string.Catagory3_Recepie29
			,R.string.Catagory3_Recepie30
			,R.string.Catagory3_Recepie31
			,R.string.Catagory3_Recepie32
			,R.string.Catagory3_Recepie33
			,R.string.Catagory3_Recepie34
			,R.string.Catagory3_Recepie35
			,R.string.Catagory3_Recepie36
			,R.string.Catagory3_Recepie37
			,R.string.Catagory3_Recepie38
			,R.string.Catagory3_Recepie39
			,R.string.Catagory3_Recepie40
			,R.string.Catagory3_Recepie41
			,R.string.Catagory3_Recepie42
			,R.string.Catagory3_Recepie44
			,R.string.Catagory3_Recepie45
			,R.string.Catagory3_Recepie46
			,R.string.Catagory3_Recepie47
			,R.string.Catagory3_Recepie48
			,R.string.Catagory3_Recepie49
			,R.string.Catagory3_Recepie50
			,R.string.Catagory3_Recepie51
			,R.string.Catagory3_Recepie52
			,R.string.Catagory3_Recepie53
			,R.string.Catagory3_Recepie54
			,R.string.Catagory3_Recepie55
			,R.string.Catagory3_Recepie56
			,R.string.Catagory3_Recepie57
			,R.string.Catagory3_Recepie58
			,R.string.Catagory3_Recepie59
			,R.string.Catagory3_Recepie60
			,R.string.Catagory3_Recepie61
			,R.string.Catagory3_Recepie62
			,R.string.Catagory3_Recepie63
			,R.string.Catagory3_Recepie64
			,R.string.Catagory3_Recepie65
			,R.string.Catagory3_Recepie66
			,R.string.Catagory3_Recepie67
			,R.string.Catagory3_Recepie68
			,R.string.Catagory3_Recepie69
			,R.string.Catagory3_Recepie70
			,R.string.Catagory3_Recepie71
			,R.string.Catagory3_Recepie72
			,R.string.Catagory3_Recepie73
			,R.string.Catagory3_Recepie74
			,R.string.Catagory3_Recepie75
			,R.string.Catagory3_Recepie76
			,R.string.Catagory3_Recepie77
			,R.string.Catagory3_Recepie78
			,R.string.Catagory3_Recepie79
			,R.string.Catagory3_Recepie80
			,R.string.Catagory3_Recepie81
			,R.string.Catagory3_Recepie82
			,R.string.Catagory3_Recepie83
			,R.string.Catagory3_Recepie84
			,R.string.Catagory3_Recepie85
			,R.string.Catagory3_Recepie86
			,R.string.Catagory3_Recepie87
			,R.string.Catagory3_Recepie88
			,R.string.Catagory3_Recepie89
			,R.string.Catagory3_Recepie90},{
			R.string.Catagory4_Recepie1
			,R.string.Catagory4_Recepie2
			,R.string.Catagory4_Recepie3
			,R.string.Catagory4_Recepie4
			,R.string.Catagory4_Recepie5
			,R.string.Catagory4_Recepie6
			,R.string.Catagory4_Recepie7},{
			R.string.Catagory5_Recepie1
			,R.string.Catagory5_Recepie2
			,R.string.Catagory5_Recepie3
			,R.string.Catagory5_Recepie4
			,R.string.Catagory5_Recepie5
			,R.string.Catagory5_Recepie6
			,R.string.Catagory5_Recepie7
			,R.string.Catagory5_Recepie8
			,R.string.Catagory5_Recepie9
			,R.string.Catagory5_Recepie10
			,R.string.Catagory5_Recepie11
			,R.string.Catagory5_Recepie12
			,R.string.Catagory5_Recepie13
			,R.string.Catagory5_Recepie14
			,R.string.Catagory5_Recepie15},{
			R.string.Catagory6_Recepie1
			,R.string.Catagory6_Recepie2
			,R.string.Catagory6_Recepie3
			,R.string.Catagory6_Recepie4
			,R.string.Catagory6_Recepie5
			,R.string.Catagory6_Recepie6
			,R.string.Catagory6_Recepie7
			,R.string.Catagory6_Recepie8
			,R.string.Catagory6_Recepie9
			,R.string.Catagory6_Recepie10
			,R.string.Catagory6_Recepie11
			,R.string.Catagory6_Recepie12},{
			R.string.Catagory7_Recepie1
			,R.string.Catagory7_Recepie2
			,R.string.Catagory7_Recepie3
			,R.string.Catagory7_Recepie4
			,R.string.Catagory7_Recepie5
			,R.string.Catagory7_Recepie6
			,R.string.Catagory7_Recepie7
			,R.string.Catagory7_Recepie8
			,R.string.Catagory7_Recepie9
			,R.string.Catagory7_Recepie10
			,R.string.Catagory7_Recepie11
			,R.string.Catagory7_Recepie12
			,R.string.Catagory7_Recepie13
			,R.string.Catagory7_Recepie14
			,R.string.Catagory7_Recepie15
			,R.string.Catagory7_Recepie16
			,R.string.Catagory7_Recepie17
			,R.string.Catagory7_Recepie18
			,R.string.Catagory7_Recepie19
			,R.string.Catagory7_Recepie20
			,R.string.Catagory7_Recepie21
			,R.string.Catagory7_Recepie22
			,R.string.Catagory7_Recepie23
			,R.string.Catagory7_Recepie24
			,R.string.Catagory7_Recepie25
			,R.string.Catagory7_Recepie26
			,R.string.Catagory7_Recepie27
			,R.string.Catagory7_Recepie28
			,R.string.Catagory7_Recepie29
			,R.string.Catagory7_Recepie30
			,R.string.Catagory7_Recepie31
			,R.string.Catagory7_Recepie32
			,R.string.Catagory7_Recepie33
			,R.string.Catagory7_Recepie34
			,R.string.Catagory7_Recepie35
			,R.string.Catagory7_Recepie36
			,R.string.Catagory7_Recepie37
			,R.string.Catagory7_Recepie38
			,R.string.Catagory7_Recepie39
			,R.string.Catagory7_Recepie40
			,R.string.Catagory7_Recepie41
			,R.string.Catagory7_Recepie42
			,R.string.Catagory7_Recepie43
			,R.string.Catagory7_Recepie44
			,R.string.Catagory7_Recepie45
			,R.string.Catagory7_Recepie46
			,R.string.Catagory7_Recepie47
			,R.string.Catagory7_Recepie48
			,R.string.Catagory7_Recepie49
			,R.string.Catagory7_Recepie50
			,R.string.Catagory7_Recepie51
			,R.string.Catagory7_Recepie52
			,R.string.Catagory7_Recepie53
			,R.string.Catagory7_Recepie54
			,R.string.Catagory7_Recepie55
			,R.string.Catagory7_Recepie56
			,R.string.Catagory7_Recepie57
			,R.string.Catagory7_Recepie58
			,R.string.Catagory7_Recepie59
			,R.string.Catagory7_Recepie60
			,R.string.Catagory7_Recepie61
			,R.string.Catagory7_Recepie62
			,R.string.Catagory7_Recepie63},{
			R.string.Catagory8_Recepie1
			,R.string.Catagory8_Recepie2
			,R.string.Catagory8_Recepie3
			,R.string.Catagory8_Recepie4
			,R.string.Catagory8_Recepie5
			,R.string.Catagory8_Recepie6
			,R.string.Catagory8_Recepie7
			,R.string.Catagory8_Recepie8
			,R.string.Catagory8_Recepie9
			,R.string.Catagory8_Recepie10
			,R.string.Catagory8_Recepie11
			,R.string.Catagory8_Recepie12
			,R.string.Catagory8_Recepie13
			,R.string.Catagory8_Recepie14
			,R.string.Catagory8_Recepie15
			,R.string.Catagory8_Recepie16
			,R.string.Catagory8_Recepie17
			,R.string.Catagory8_Recepie18
			,R.string.Catagory8_Recepie19
			,R.string.Catagory8_Recepie20
			,R.string.Catagory8_Recepie21
			,R.string.Catagory8_Recepie22
			,R.string.Catagory8_Recepie23
			,R.string.Catagory8_Recepie24},{
			R.string.Catagory9_Recepie1
			,R.string.Catagory9_Recepie2
			,R.string.Catagory9_Recepie3},{
			R.string.Catagory10_Recepie1},{
			R.string.Catagory11_Recepie1}
			};
			
	int Ingredients_Names[][] = {{R.string.Catagory1_Ingredients1
			,R.string.Catagory1_Ingredients2
			,R.string.Catagory1_Ingredients3
			,R.string.Catagory1_Ingredients4
			,R.string.Catagory1_Ingredients5
			,R.string.Catagory1_Ingredients6
			,R.string.Catagory1_Ingredients7
			,R.string.Catagory1_Ingredients8
			,R.string.Catagory1_Ingredients9
			,R.string.Catagory1_Ingredients10
			,R.string.Catagory1_Ingredients11},{
			R.string.Catagory2_Ingredients1
			,R.string.Catagory2_Ingredients2
			,R.string.Catagory2_Ingredients3
			,R.string.Catagory2_Ingredients4
			,R.string.Catagory2_Ingredients5
			,R.string.Catagory2_Ingredients6
			,R.string.Catagory2_Ingredients7
			,R.string.Catagory2_Ingredients8
			,R.string.Catagory2_Ingredients9
			,R.string.Catagory2_Ingredients10
			,R.string.Catagory2_Ingredients11
			,R.string.Catagory2_Ingredients12
			,R.string.Catagory2_Ingredients13
			,R.string.Catagory2_Ingredients14
			,R.string.Catagory2_Ingredients15
			,R.string.Catagory2_Ingredients16
			,R.string.Catagory2_Ingredients17
			,R.string.Catagory2_Ingredients18
			,R.string.Catagory2_Ingredients19
			,R.string.Catagory2_Ingredients20
			,R.string.Catagory2_Ingredients21
			,R.string.Catagory2_Ingredients22
			,R.string.Catagory2_Ingredients23
			,R.string.Catagory2_Ingredients25
			,R.string.Catagory2_Ingredients26
			,R.string.Catagory2_Ingredients27
			,R.string.Catagory2_Ingredients28
			,R.string.Catagory2_Ingredients29
			,R.string.Catagory2_Ingredients30
			,R.string.Catagory2_Ingredients31
			,R.string.Catagory2_Ingredients32
			,R.string.Catagory2_Ingredients33
			,R.string.Catagory2_Ingredients34
			,R.string.Catagory2_Ingredients35
			,R.string.Catagory2_Ingredients37
			,R.string.Catagory2_Ingredients38
			,R.string.Catagory2_Ingredients39
			,R.string.Catagory2_Ingredients40
			,R.string.Catagory2_Ingredients41
			,R.string.Catagory2_Ingredients42
			,R.string.Catagory2_Ingredients43
			,R.string.Catagory2_Ingredients44
			,R.string.Catagory2_Ingredients45
			,R.string.Catagory2_Ingredients46
			,R.string.Catagory2_Ingredients47
			,R.string.Catagory2_Ingredients48
			,R.string.Catagory2_Ingredients49
			,R.string.Catagory2_Ingredients50
			,R.string.Catagory2_Ingredients51},{
			R.string.Catagory3_Ingredients1
			,R.string.Catagory3_Ingredients2
			,R.string.Catagory3_Ingredients3
			,R.string.Catagory3_Ingredients4
			,R.string.Catagory3_Ingredients5
			,R.string.Catagory3_Ingredients6
			,R.string.Catagory3_Ingredients7
			,R.string.Catagory3_Ingredients8
			,R.string.Catagory3_Ingredients9
			,R.string.Catagory3_Ingredients10
			,R.string.Catagory3_Ingredients11
			,R.string.Catagory3_Ingredients12
			,R.string.Catagory3_Ingredients13
			,R.string.Catagory3_Ingredients14
			,R.string.Catagory3_Ingredients15
			,R.string.Catagory3_Ingredients16
			,R.string.Catagory3_Ingredients17
			,R.string.Catagory3_Ingredients18
			,R.string.Catagory3_Ingredients19
			,R.string.Catagory3_Ingredients20
			,R.string.Catagory3_Ingredients21
			,R.string.Catagory3_Ingredients22
			,R.string.Catagory3_Ingredients23
			,R.string.Catagory3_Ingredients24
			,R.string.Catagory3_Ingredients25
			,R.string.Catagory3_Ingredients26
			,R.string.Catagory3_Ingredients27
			,R.string.Catagory3_Ingredients28
			,R.string.Catagory3_Ingredients29
			,R.string.Catagory3_Ingredients30
			,R.string.Catagory3_Ingredients31
			,R.string.Catagory3_Ingredients32
			,R.string.Catagory3_Ingredients33
			,R.string.Catagory3_Ingredients34
			,R.string.Catagory3_Ingredients35
			,R.string.Catagory3_Ingredients36
			,R.string.Catagory3_Ingredients37
			,R.string.Catagory3_Ingredients38
			,R.string.Catagory3_Ingredients39
			,R.string.Catagory3_Ingredients40
			,R.string.Catagory3_Ingredients41
			,R.string.Catagory3_Ingredients42
			,R.string.Catagory3_Ingredients44
			,R.string.Catagory3_Ingredients45
			,R.string.Catagory3_Ingredients46
			,R.string.Catagory3_Ingredients47
			,R.string.Catagory3_Ingredients48
			,R.string.Catagory3_Ingredients49
			,R.string.Catagory3_Ingredients50
			,R.string.Catagory3_Ingredients51
			,R.string.Catagory3_Ingredients52
			,R.string.Catagory3_Ingredients53
			,R.string.Catagory3_Ingredients54
			,R.string.Catagory3_Ingredients55
			,R.string.Catagory3_Ingredients56
			,R.string.Catagory3_Ingredients57
			,R.string.Catagory3_Ingredients58
			,R.string.Catagory3_Ingredients59
			,R.string.Catagory3_Ingredients60
			,R.string.Catagory3_Ingredients61
			,R.string.Catagory3_Ingredients62
			,R.string.Catagory3_Ingredients63
			,R.string.Catagory3_Ingredients64
			,R.string.Catagory3_Ingredients65
			,R.string.Catagory3_Ingredients66
			,R.string.Catagory3_Ingredients67
			,R.string.Catagory3_Ingredients68
			,R.string.Catagory3_Ingredients69
			,R.string.Catagory3_Ingredients70
			,R.string.Catagory3_Ingredients71
			,R.string.Catagory3_Ingredients72
			,R.string.Catagory3_Ingredients73
			,R.string.Catagory3_Ingredients74
			,R.string.Catagory3_Ingredients75
			,R.string.Catagory3_Ingredients76
			,R.string.Catagory3_Ingredients77
			,R.string.Catagory3_Ingredients78
			,R.string.Catagory3_Ingredients79
			,R.string.Catagory3_Ingredients80
			,R.string.Catagory3_Ingredients81
			,R.string.Catagory3_Ingredients82
			,R.string.Catagory3_Ingredients83
			,R.string.Catagory3_Ingredients84
			,R.string.Catagory3_Ingredients85
			,R.string.Catagory3_Ingredients86
			,R.string.Catagory3_Ingredients87
			,R.string.Catagory3_Ingredients88
			,R.string.Catagory3_Ingredients89
			,R.string.Catagory3_Ingredients90},{
			R.string.Catagory4_Ingredients1
			,R.string.Catagory4_Ingredients2
			,R.string.Catagory4_Ingredients3
			,R.string.Catagory4_Ingredients4
			,R.string.Catagory4_Ingredients5
			,R.string.Catagory4_Ingredients6
			,R.string.Catagory4_Ingredients7},{
			R.string.Catagory5_Ingredients1
			,R.string.Catagory5_Ingredients2
			,R.string.Catagory5_Ingredients3
			,R.string.Catagory5_Ingredients4
			,R.string.Catagory5_Ingredients5
			,R.string.Catagory5_Ingredients6
			,R.string.Catagory5_Ingredients7
			,R.string.Catagory5_Ingredients8
			,R.string.Catagory5_Ingredients9
			,R.string.Catagory5_Ingredients10
			,R.string.Catagory5_Ingredients11
			,R.string.Catagory5_Ingredients12
			,R.string.Catagory5_Ingredients13
			,R.string.Catagory5_Ingredients14
			,R.string.Catagory5_Ingredients15},{
			R.string.Catagory6_Ingredients1
			,R.string.Catagory6_Ingredients2
			,R.string.Catagory6_Ingredients3
			,R.string.Catagory6_Ingredients4
			,R.string.Catagory6_Ingredients5
			,R.string.Catagory6_Ingredients6
			,R.string.Catagory6_Ingredients7
			,R.string.Catagory6_Ingredients8
			,R.string.Catagory6_Ingredients9
			,R.string.Catagory6_Ingredients10
			,R.string.Catagory6_Ingredients11
			,R.string.Catagory6_Ingredients12},{
			R.string.Catagory7_Ingredients1
			,R.string.Catagory7_Ingredients2
			,R.string.Catagory7_Ingredients3
			,R.string.Catagory7_Ingredients4
			,R.string.Catagory7_Ingredients5
			,R.string.Catagory7_Ingredients6
			,R.string.Catagory7_Ingredients7
			,R.string.Catagory7_Ingredients8
			,R.string.Catagory7_Ingredients9
			,R.string.Catagory7_Ingredients10
			,R.string.Catagory7_Ingredients11
			,R.string.Catagory7_Ingredients12
			,R.string.Catagory7_Ingredients13
			,R.string.Catagory7_Ingredients14
			,R.string.Catagory7_Ingredients15
			,R.string.Catagory7_Ingredients16
			,R.string.Catagory7_Ingredients17
			,R.string.Catagory7_Ingredients18
			,R.string.Catagory7_Ingredients19
			,R.string.Catagory7_Ingredients20
			,R.string.Catagory7_Ingredients21
			,R.string.Catagory7_Ingredients22
			,R.string.Catagory7_Ingredients23
			,R.string.Catagory7_Ingredients24
			,R.string.Catagory7_Ingredients25
			,R.string.Catagory7_Ingredients26
			,R.string.Catagory7_Ingredients27
			,R.string.Catagory7_Ingredients28
			,R.string.Catagory7_Ingredients29
			,R.string.Catagory7_Ingredients30
			,R.string.Catagory7_Ingredients31
			,R.string.Catagory7_Ingredients32
			,R.string.Catagory7_Ingredients33
			,R.string.Catagory7_Ingredients34
			,R.string.Catagory7_Ingredients35
			,R.string.Catagory7_Ingredients36
			,R.string.Catagory7_Ingredients37
			,R.string.Catagory7_Ingredients38
			,R.string.Catagory7_Ingredients39
			,R.string.Catagory7_Ingredients40
			,R.string.Catagory7_Ingredients41
			,R.string.Catagory7_Ingredients42
			,R.string.Catagory7_Ingredients43
			,R.string.Catagory7_Ingredients44
			,R.string.Catagory7_Ingredients45
			,R.string.Catagory7_Ingredients46
			,R.string.Catagory7_Ingredients47
			,R.string.Catagory7_Ingredients48
			,R.string.Catagory7_Ingredients49
			,R.string.Catagory7_Ingredients50
			,R.string.Catagory7_Ingredients51
			,R.string.Catagory7_Ingredients52
			,R.string.Catagory7_Ingredients53
			,R.string.Catagory7_Ingredients54
			,R.string.Catagory7_Ingredients55
			,R.string.Catagory7_Ingredients56
			,R.string.Catagory7_Ingredients57
			,R.string.Catagory7_Ingredients58
			,R.string.Catagory7_Ingredients59
			,R.string.Catagory7_Ingredients60
			,R.string.Catagory7_Ingredients61
			,R.string.Catagory7_Ingredients62
			,R.string.Catagory7_Ingredients63},{
			R.string.Catagory8_Ingredients1
			,R.string.Catagory8_Ingredients2
			,R.string.Catagory8_Ingredients3
			,R.string.Catagory8_Ingredients4
			,R.string.Catagory8_Ingredients5
			,R.string.Catagory8_Ingredients6
			,R.string.Catagory8_Ingredients7
			,R.string.Catagory8_Ingredients8
			,R.string.Catagory8_Ingredients9
			,R.string.Catagory8_Ingredients10
			,R.string.Catagory8_Ingredients11
			,R.string.Catagory8_Ingredients12
			,R.string.Catagory8_Ingredients13
			,R.string.Catagory8_Ingredients14
			,R.string.Catagory8_Ingredients15
			,R.string.Catagory8_Ingredients16
			,R.string.Catagory8_Ingredients17
			,R.string.Catagory8_Ingredients18
			,R.string.Catagory8_Ingredients19
			,R.string.Catagory8_Ingredients20
			,R.string.Catagory8_Ingredients21
			,R.string.Catagory8_Ingredients22
			,R.string.Catagory8_Ingredients23
			,R.string.Catagory8_Ingredients24},{
			R.string.Catagory9_Ingredients1
			,R.string.Catagory9_Ingredients2
			,R.string.Catagory9_Ingredients3},{
			R.string.Catagory10_Ingredients1},{
			R.string.Catagory11_Ingredients1}
};
			
	int Method_Names[][] = {{R.string.Catagory1_Method1
			,R.string.Catagory1_Method2
			,R.string.Catagory1_Method3
			,R.string.Catagory1_Method4
			,R.string.Catagory1_Method5
			,R.string.Catagory1_Method6
			,R.string.Catagory1_Method7
			,R.string.Catagory1_Method8
			,R.string.Catagory1_Method9
			,R.string.Catagory1_Method10
			,R.string.Catagory1_Method11},{
			R.string.Catagory2_Method1
			,R.string.Catagory2_Method2
			,R.string.Catagory2_Method3
			,R.string.Catagory2_Method4
			,R.string.Catagory2_Method5
			,R.string.Catagory2_Method6
			,R.string.Catagory2_Method7
			,R.string.Catagory2_Method8
			,R.string.Catagory2_Method9
			,R.string.Catagory2_Method10
			,R.string.Catagory2_Method11
			,R.string.Catagory2_Method12
			,R.string.Catagory2_Method13
			,R.string.Catagory2_Method14
			,R.string.Catagory2_Method15
			,R.string.Catagory2_Method16
			,R.string.Catagory2_Method17
			,R.string.Catagory2_Method18
			,R.string.Catagory2_Method19
			,R.string.Catagory2_Method20
			,R.string.Catagory2_Method21
			,R.string.Catagory2_Method22
			,R.string.Catagory2_Method23
			,R.string.Catagory2_Method25
			,R.string.Catagory2_Method26
			,R.string.Catagory2_Method27
			,R.string.Catagory2_Method28
			,R.string.Catagory2_Method29
			,R.string.Catagory2_Method30
			,R.string.Catagory2_Method31
			,R.string.Catagory2_Method32
			,R.string.Catagory2_Method33
			,R.string.Catagory2_Method34
			,R.string.Catagory2_Method35
			,R.string.Catagory2_Method37
			,R.string.Catagory2_Method38
			,R.string.Catagory2_Method39
			,R.string.Catagory2_Method40
			,R.string.Catagory2_Method41
			,R.string.Catagory2_Method42
			,R.string.Catagory2_Method43
			,R.string.Catagory2_Method44
			,R.string.Catagory2_Method45
			,R.string.Catagory2_Method46
			,R.string.Catagory2_Method47
			,R.string.Catagory2_Method48
			,R.string.Catagory2_Method49
			,R.string.Catagory2_Method50
			,R.string.Catagory2_Method51},{
			R.string.Catagory3_Method1
			,R.string.Catagory3_Method2
			,R.string.Catagory3_Method3
			,R.string.Catagory3_Method4
			,R.string.Catagory3_Method5
			,R.string.Catagory3_Method6
			,R.string.Catagory3_Method7
			,R.string.Catagory3_Method8
			,R.string.Catagory3_Method9
			,R.string.Catagory3_Method10
			,R.string.Catagory3_Method11
			,R.string.Catagory3_Method12
			,R.string.Catagory3_Method13
			,R.string.Catagory3_Method14
			,R.string.Catagory3_Method15
			,R.string.Catagory3_Method16
			,R.string.Catagory3_Method17
			,R.string.Catagory3_Method18
			,R.string.Catagory3_Method19
			,R.string.Catagory3_Method20
			,R.string.Catagory3_Method21
			,R.string.Catagory3_Method22
			,R.string.Catagory3_Method23
			,R.string.Catagory3_Method24
			,R.string.Catagory3_Method25
			,R.string.Catagory3_Method26
			,R.string.Catagory3_Method27
			,R.string.Catagory3_Method28
			,R.string.Catagory3_Method29
			,R.string.Catagory3_Method30
			,R.string.Catagory3_Method31
			,R.string.Catagory3_Method32
			,R.string.Catagory3_Method33
			,R.string.Catagory3_Method34
			,R.string.Catagory3_Method35
			,R.string.Catagory3_Method36
			,R.string.Catagory3_Method37
			,R.string.Catagory3_Method38
			,R.string.Catagory3_Method39
			,R.string.Catagory3_Method40
			,R.string.Catagory3_Method41
			,R.string.Catagory3_Method42
			,R.string.Catagory3_Method44
			,R.string.Catagory3_Method45
			,R.string.Catagory3_Method46
			,R.string.Catagory3_Method47
			,R.string.Catagory3_Method48
			,R.string.Catagory3_Method49
			,R.string.Catagory3_Method50
			,R.string.Catagory3_Method51
			,R.string.Catagory3_Method52
			,R.string.Catagory3_Method53
			,R.string.Catagory3_Method54
			,R.string.Catagory3_Method55
			,R.string.Catagory3_Method56
			,R.string.Catagory3_Method57
			,R.string.Catagory3_Method58
			,R.string.Catagory3_Method59
			,R.string.Catagory3_Method60
			,R.string.Catagory3_Method61
			,R.string.Catagory3_Method62
			,R.string.Catagory3_Method63
			,R.string.Catagory3_Method64
			,R.string.Catagory3_Method65
			,R.string.Catagory3_Method66
			,R.string.Catagory3_Method67
			,R.string.Catagory3_Method68
			,R.string.Catagory3_Method69
			,R.string.Catagory3_Method70
			,R.string.Catagory3_Method71
			,R.string.Catagory3_Method72
			,R.string.Catagory3_Method73
			,R.string.Catagory3_Method74
			,R.string.Catagory3_Method75
			,R.string.Catagory3_Method76
			,R.string.Catagory3_Method77
			,R.string.Catagory3_Method78
			,R.string.Catagory3_Method79
			,R.string.Catagory3_Method80
			,R.string.Catagory3_Method81
			,R.string.Catagory3_Method82
			,R.string.Catagory3_Method83
			,R.string.Catagory3_Method84
			,R.string.Catagory3_Method85
			,R.string.Catagory3_Method86
			,R.string.Catagory3_Method87
			,R.string.Catagory3_Method88
			,R.string.Catagory3_Method89
			,R.string.Catagory3_Method90},{
			R.string.Catagory4_Method1
			,R.string.Catagory4_Method2
			,R.string.Catagory4_Method3
			,R.string.Catagory4_Method4
			,R.string.Catagory4_Method5
			,R.string.Catagory4_Method6
			,R.string.Catagory4_Method7},{
			R.string.Catagory5_Method1
			,R.string.Catagory5_Method2
			,R.string.Catagory5_Method3
			,R.string.Catagory5_Method4
			,R.string.Catagory5_Method5
			,R.string.Catagory5_Method6
			,R.string.Catagory5_Method7
			,R.string.Catagory5_Method8
			,R.string.Catagory5_Method9
			,R.string.Catagory5_Method10
			,R.string.Catagory5_Method11
			,R.string.Catagory5_Method12
			,R.string.Catagory5_Method13
			,R.string.Catagory5_Method14
			,R.string.Catagory5_Method15},{
			R.string.Catagory6_Method1
			,R.string.Catagory6_Method2
			,R.string.Catagory6_Method3
			,R.string.Catagory6_Method4
			,R.string.Catagory6_Method5
			,R.string.Catagory6_Method6
			,R.string.Catagory6_Method7
			,R.string.Catagory6_Method8
			,R.string.Catagory6_Method9
			,R.string.Catagory6_Method10
			,R.string.Catagory6_Method11
			,R.string.Catagory6_Method12},{
			R.string.Catagory7_Method1
			,R.string.Catagory7_Method2
			,R.string.Catagory7_Method3
			,R.string.Catagory7_Method4
			,R.string.Catagory7_Method5
			,R.string.Catagory7_Method6
			,R.string.Catagory7_Method7
			,R.string.Catagory7_Method8
			,R.string.Catagory7_Method9
			,R.string.Catagory7_Method10
			,R.string.Catagory7_Method11
			,R.string.Catagory7_Method12
			,R.string.Catagory7_Method13
			,R.string.Catagory7_Method14
			,R.string.Catagory7_Method15
			,R.string.Catagory7_Method16
			,R.string.Catagory7_Method17
			,R.string.Catagory7_Method18
			,R.string.Catagory7_Method19
			,R.string.Catagory7_Method20
			,R.string.Catagory7_Method21
			,R.string.Catagory7_Method22
			,R.string.Catagory7_Method23
			,R.string.Catagory7_Method24
			,R.string.Catagory7_Method25
			,R.string.Catagory7_Method26
			,R.string.Catagory7_Method27
			,R.string.Catagory7_Method28
			,R.string.Catagory7_Method29
			,R.string.Catagory7_Method30
			,R.string.Catagory7_Method31
			,R.string.Catagory7_Method32
			,R.string.Catagory7_Method33
			,R.string.Catagory7_Method34
			,R.string.Catagory7_Method35
			,R.string.Catagory7_Method36
			,R.string.Catagory7_Method37
			,R.string.Catagory7_Method38
			,R.string.Catagory7_Method39
			,R.string.Catagory7_Method40
			,R.string.Catagory7_Method41
			,R.string.Catagory7_Method42
			,R.string.Catagory7_Method43
			,R.string.Catagory7_Method44
			,R.string.Catagory7_Method45
			,R.string.Catagory7_Method46
			,R.string.Catagory7_Method47
			,R.string.Catagory7_Method48
			,R.string.Catagory7_Method49
			,R.string.Catagory7_Method50
			,R.string.Catagory7_Method51
			,R.string.Catagory7_Method52
			,R.string.Catagory7_Method53
			,R.string.Catagory7_Method54
			,R.string.Catagory7_Method55
			,R.string.Catagory7_Method56
			,R.string.Catagory7_Method57
			,R.string.Catagory7_Method58
			,R.string.Catagory7_Method59
			,R.string.Catagory7_Method60
			,R.string.Catagory7_Method61
			,R.string.Catagory7_Method62
			,R.string.Catagory7_Method63},{
			R.string.Catagory8_Method1
			,R.string.Catagory8_Method2
			,R.string.Catagory8_Method3
			,R.string.Catagory8_Method4
			,R.string.Catagory8_Method5
			,R.string.Catagory8_Method6
			,R.string.Catagory8_Method7
			,R.string.Catagory8_Method8
			,R.string.Catagory8_Method9
			,R.string.Catagory8_Method10
			,R.string.Catagory8_Method11
			,R.string.Catagory8_Method12
			,R.string.Catagory8_Method13
			,R.string.Catagory8_Method14
			,R.string.Catagory8_Method15
			,R.string.Catagory8_Method16
			,R.string.Catagory8_Method17
			,R.string.Catagory8_Method18
			,R.string.Catagory8_Method19
			,R.string.Catagory8_Method20
			,R.string.Catagory8_Method21
			,R.string.Catagory8_Method22
			,R.string.Catagory8_Method23
			,R.string.Catagory8_Method24},{
			R.string.Catagory9_Method1
			,R.string.Catagory9_Method2
			,R.string.Catagory9_Method3},{
			R.string.Catagory10_Method1},{
			R.string.Catagory11_Method1}
};
			
	int Time_Names[][] = {{R.string.Catagory1_Time1
			,R.string.Catagory1_Time2
			,R.string.Catagory1_Time3
			,R.string.Catagory1_Time4
			,R.string.Catagory1_Time5
			,R.string.Catagory1_Time6
			,R.string.Catagory1_Time7
			,R.string.Catagory1_Time8
			,R.string.Catagory1_Time9
			,R.string.Catagory1_Time10
			,R.string.Catagory1_Time11},{
			R.string.Catagory2_Time1
			,R.string.Catagory2_Time2
			,R.string.Catagory2_Time3
			,R.string.Catagory2_Time4
			,R.string.Catagory2_Time5
			,R.string.Catagory2_Time6
			,R.string.Catagory2_Time7
			,R.string.Catagory2_Time8
			,R.string.Catagory2_Time9
			,R.string.Catagory2_Time10
			,R.string.Catagory2_Time11
			,R.string.Catagory2_Time12
			,R.string.Catagory2_Time13
			,R.string.Catagory2_Time14
			,R.string.Catagory2_Time15
			,R.string.Catagory2_Time16
			,R.string.Catagory2_Time17
			,R.string.Catagory2_Time18
			,R.string.Catagory2_Time19
			,R.string.Catagory2_Time20
			,R.string.Catagory2_Time21
			,R.string.Catagory2_Time22
			,R.string.Catagory2_Time23
			,R.string.Catagory2_Time25
			,R.string.Catagory2_Time26
			,R.string.Catagory2_Time27
			,R.string.Catagory2_Time28
			,R.string.Catagory2_Time29
			,R.string.Catagory2_Time30
			,R.string.Catagory2_Time31
			,R.string.Catagory2_Time32
			,R.string.Catagory2_Time33
			,R.string.Catagory2_Time34
			,R.string.Catagory2_Time35
			,R.string.Catagory2_Time37
			,R.string.Catagory2_Time38
			,R.string.Catagory2_Time39
			,R.string.Catagory2_Time40
			,R.string.Catagory2_Time41
			,R.string.Catagory2_Time42
			,R.string.Catagory2_Time43
			,R.string.Catagory2_Time44
			,R.string.Catagory2_Time45
			,R.string.Catagory2_Time46
			,R.string.Catagory2_Time47
			,R.string.Catagory2_Time48
			,R.string.Catagory2_Time49
			,R.string.Catagory2_Time50
			,R.string.Catagory2_Time51},{
			R.string.Catagory3_Time1
			,R.string.Catagory3_Time2
			,R.string.Catagory3_Time3
			,R.string.Catagory3_Time4
			,R.string.Catagory3_Time5
			,R.string.Catagory3_Time6
			,R.string.Catagory3_Time7
			,R.string.Catagory3_Time8
			,R.string.Catagory3_Time9
			,R.string.Catagory3_Time10
			,R.string.Catagory3_Time11
			,R.string.Catagory3_Time12
			,R.string.Catagory3_Time13
			,R.string.Catagory3_Time14
			,R.string.Catagory3_Time15
			,R.string.Catagory3_Time16
			,R.string.Catagory3_Time17
			,R.string.Catagory3_Time18
			,R.string.Catagory3_Time19
			,R.string.Catagory3_Time20
			,R.string.Catagory3_Time21
			,R.string.Catagory3_Time22
			,R.string.Catagory3_Time23
			,R.string.Catagory3_Time24
			,R.string.Catagory3_Time25
			,R.string.Catagory3_Time26
			,R.string.Catagory3_Time27
			,R.string.Catagory3_Time28
			,R.string.Catagory3_Time29
			,R.string.Catagory3_Time30
			,R.string.Catagory3_Time31
			,R.string.Catagory3_Time32
			,R.string.Catagory3_Time33
			,R.string.Catagory3_Time34
			,R.string.Catagory3_Time35
			,R.string.Catagory3_Time36
			,R.string.Catagory3_Time37
			,R.string.Catagory3_Time38
			,R.string.Catagory3_Time39
			,R.string.Catagory3_Time40
			,R.string.Catagory3_Time41
			,R.string.Catagory3_Time42
			,R.string.Catagory3_Time44
			,R.string.Catagory3_Time45
			,R.string.Catagory3_Time46
			,R.string.Catagory3_Time47
			,R.string.Catagory3_Time48
			,R.string.Catagory3_Time49
			,R.string.Catagory3_Time50
			,R.string.Catagory3_Time51
			,R.string.Catagory3_Time52
			,R.string.Catagory3_Time53
			,R.string.Catagory3_Time54
			,R.string.Catagory3_Time55
			,R.string.Catagory3_Time56
			,R.string.Catagory3_Time57
			,R.string.Catagory3_Time58
			,R.string.Catagory3_Time59
			,R.string.Catagory3_Time60
			,R.string.Catagory3_Time61
			,R.string.Catagory3_Time62
			,R.string.Catagory3_Time63
			,R.string.Catagory3_Time64
			,R.string.Catagory3_Time65
			,R.string.Catagory3_Time66
			,R.string.Catagory3_Time67
			,R.string.Catagory3_Time68
			,R.string.Catagory3_Time69
			,R.string.Catagory3_Time70
			,R.string.Catagory3_Time71
			,R.string.Catagory3_Time72
			,R.string.Catagory3_Time73
			,R.string.Catagory3_Time74
			,R.string.Catagory3_Time75
			,R.string.Catagory3_Time76
			,R.string.Catagory3_Time77
			,R.string.Catagory3_Time78
			,R.string.Catagory3_Time79
			,R.string.Catagory3_Time80
			,R.string.Catagory3_Time81
			,R.string.Catagory3_Time82
			,R.string.Catagory3_Time83
			,R.string.Catagory3_Time84
			,R.string.Catagory3_Time85
			,R.string.Catagory3_Time86
			,R.string.Catagory3_Time87
			,R.string.Catagory3_Time88
			,R.string.Catagory3_Time89
			,R.string.Catagory3_Time90},{
			R.string.Catagory4_Time1
			,R.string.Catagory4_Time2
			,R.string.Catagory4_Time3
			,R.string.Catagory4_Time4
			,R.string.Catagory4_Time5
			,R.string.Catagory4_Time6
			,R.string.Catagory4_Time7},{
			R.string.Catagory5_Time1
			,R.string.Catagory5_Time2
			,R.string.Catagory5_Time3
			,R.string.Catagory5_Time4
			,R.string.Catagory5_Time5
			,R.string.Catagory5_Time6
			,R.string.Catagory5_Time7
			,R.string.Catagory5_Time8
			,R.string.Catagory5_Time9
			,R.string.Catagory5_Time10
			,R.string.Catagory5_Time11
			,R.string.Catagory5_Time12
			,R.string.Catagory5_Time13
			,R.string.Catagory5_Time14
			,R.string.Catagory5_Time15},{
			R.string.Catagory6_Time1
			,R.string.Catagory6_Time2
			,R.string.Catagory6_Time3
			,R.string.Catagory6_Time4
			,R.string.Catagory6_Time5
			,R.string.Catagory6_Time6
			,R.string.Catagory6_Time7
			,R.string.Catagory6_Time8
			,R.string.Catagory6_Time9
			,R.string.Catagory6_Time10
			,R.string.Catagory6_Time11
			,R.string.Catagory6_Time12},{
			R.string.Catagory7_Time1
			,R.string.Catagory7_Time2
			,R.string.Catagory7_Time3
			,R.string.Catagory7_Time4
			,R.string.Catagory7_Time5
			,R.string.Catagory7_Time6
			,R.string.Catagory7_Time7
			,R.string.Catagory7_Time8
			,R.string.Catagory7_Time9
			,R.string.Catagory7_Time10
			,R.string.Catagory7_Time11
			,R.string.Catagory7_Time12
			,R.string.Catagory7_Time13
			,R.string.Catagory7_Time14
			,R.string.Catagory7_Time15
			,R.string.Catagory7_Time16
			,R.string.Catagory7_Time17
			,R.string.Catagory7_Time18
			,R.string.Catagory7_Time19
			,R.string.Catagory7_Time20
			,R.string.Catagory7_Time21
			,R.string.Catagory7_Time22
			,R.string.Catagory7_Time23
			,R.string.Catagory7_Time24
			,R.string.Catagory7_Time25
			,R.string.Catagory7_Time26
			,R.string.Catagory7_Time27
			,R.string.Catagory7_Time28
			,R.string.Catagory7_Time29
			,R.string.Catagory7_Time30
			,R.string.Catagory7_Time31
			,R.string.Catagory7_Time32
			,R.string.Catagory7_Time33
			,R.string.Catagory7_Time34
			,R.string.Catagory7_Time35
			,R.string.Catagory7_Time36
			,R.string.Catagory7_Time37
			,R.string.Catagory7_Time38
			,R.string.Catagory7_Time39
			,R.string.Catagory7_Time40
			,R.string.Catagory7_Time41
			,R.string.Catagory7_Time42
			,R.string.Catagory7_Time43
			,R.string.Catagory7_Time44
			,R.string.Catagory7_Time45
			,R.string.Catagory7_Time46
			,R.string.Catagory7_Time47
			,R.string.Catagory7_Time48
			,R.string.Catagory7_Time49
			,R.string.Catagory7_Time50
			,R.string.Catagory7_Time51
			,R.string.Catagory7_Time52
			,R.string.Catagory7_Time53
			,R.string.Catagory7_Time54
			,R.string.Catagory7_Time55
			,R.string.Catagory7_Time56
			,R.string.Catagory7_Time57
			,R.string.Catagory7_Time58
			,R.string.Catagory7_Time59
			,R.string.Catagory7_Time60
			,R.string.Catagory7_Time61
			,R.string.Catagory7_Time62
			,R.string.Catagory7_Time63},{
			R.string.Catagory8_Time1
			,R.string.Catagory8_Time2
			,R.string.Catagory8_Time3
			,R.string.Catagory8_Time4
			,R.string.Catagory8_Time5
			,R.string.Catagory8_Time6
			,R.string.Catagory8_Time7
			,R.string.Catagory8_Time8
			,R.string.Catagory8_Time9
			,R.string.Catagory8_Time10
			,R.string.Catagory8_Time11
			,R.string.Catagory8_Time12
			,R.string.Catagory8_Time13
			,R.string.Catagory8_Time14
			,R.string.Catagory8_Time15
			,R.string.Catagory8_Time16
			,R.string.Catagory8_Time17
			,R.string.Catagory8_Time18
			,R.string.Catagory8_Time19
			,R.string.Catagory8_Time20
			,R.string.Catagory8_Time21
			,R.string.Catagory8_Time22
			,R.string.Catagory8_Time23
			,R.string.Catagory8_Time24},{
			R.string.Catagory9_Time1
			,R.string.Catagory9_Time2
			,R.string.Catagory9_Time3},{
			R.string.Catagory10_Time1},{
			R.string.Catagory11_Time1}
};
			
	TextView Rec_name,Ing_txt,Method_txt,Remark_txt;
	@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.description);
        Rec_name = (TextView) findViewById(R.id.RecipeName);
        Ing_txt = (TextView) findViewById(R.id.IngredientsTxt);
        Method_txt = (TextView) findViewById(R.id.MethodTxt);
        Remark_txt = (TextView) findViewById(R.id.RemarksTxt);
        int position = getIntent().getExtras().getInt("PositionValue");
        Rec_name.setText(getResources().getString(Recipe_Names[Recipes.m_categorySel][position]));
        Ing_txt.setText(getResources().getString(Ingredients_Names[Recipes.m_categorySel][position]));
        Method_txt.setText(getResources().getString(Method_Names[Recipes.m_categorySel][position]));
        Remark_txt.setText(getResources().getString(Time_Names[Recipes.m_categorySel][position]));
	}
}
